### ISSUE TITLE
Multi boot support

### ISSUE THREAD

**Issue by vamega** [Torxed/archinstall#51]
Would you be interested/open to contributions that allow for installations that need to co-exist with other installations of operating systems?

**Comment by Torxed** [comment]
Absolutely.
The main goal of this installer is to support it, and to some extent do. The partition-step would need to become a tiny bit more complicated, but if you have other ideas I greatly welcome PR's and I'll evaluate them : )

**Comment by Torxed** [comment]
Currently working on a "skip partitioning" step for now, which will use whatever existing partitioning there is.
This requires a manual intervention before running the installer.

1. parted <drive>
2. python -m archinstall

Ideally, the guided template would have steps to guide through partitioning.
But because that would require slightly more UI glue code to work, I'm waiting with it.

Currently in testing locally to see if this approach is valid.
(dualbooting Windows + Arch from the same drive).

The installer as it stands today has dualboot support, but not if they're on the same drive.

**Comment by Torxed** [comment]
Also adding a `archinstall.harddrive('/dev/sda').operating_system` to detect if there's multiple, and then the installer will gracefully suggest to only use the unused space if possible. But it's a bit tricky to get right :)

**Comment by Torxed** [comment]
This is partially fixed in #112.
When drives are selected for the installation, the installation will detect existing partitions and ask what to do.
If option `2` is selected, partitions can be selected for the installation - which will exclude partitions for the current installation.

The installer will also leave the boot partition un-formatted and simply install another EFI loader.
This should enable multi-boot support with OSX, Windows, BSD and other Linux distributions *(assuming they all boot in UEFI mode)*. If other Arch Linux installations exists, there might be a collision with the `systemd-bootd` loader configuration file since it's sort of hardcoded to [arch.html](https://github.com/Torxed/archinstall/blob/master/archinstall/lib/installer.py#L315-L325).

Before I officially close this issue and confirm this as fixed, this hardcoded filename has to change.
We could generate a random filename, but we could also use the hostname chosen. For instance `f'{self.mountpoint}/boot/loader/entries/<hostname>.conf`.

To avoid cluttering the `/boot` partition we could add optional cleanup finding old configurations containing a watermark `# archinstall` and detect if the drives are pointing to the identical drive we're formatting - and if that is `True` safely remove entries tied to the specified partition/drive that's being wiped anyway.

**Comment by Torxed** [comment]
This should now be supported and fully functional.
It's not been tested extensively, but it has been tested - but requires additional tests before next release.
