### ISSUE TITLE
archlinux.life is down

### ISSUE THREAD

**Issue by zurchpet** [Torxed/archinstall#80]
https://downforeveryoneorjustme.com/archlinux.life?proto=https

Can't reach archlinux.life.

**Comment by Torxed** [comment]
@zurchpet It's up again, although this server conf is a bit shaky so I'll have to really double down on making that more stable. It will most likely go down once more within 24h because there's some dependencies that doesn't want to co-operate. I'll keep an eye on it and fix it in the weekend :) I'll leave this open for now until it's done.

Cheers for reporting! :)

**Comment by zurchpet** [comment]
Thank you :)
